print("********************************************")
print("\t   PERSONAL INFORMATION")
print("********************************************")

firstName= input(" Enter First Name: ")
middleName= input("Enter Middle Name: ")
lastName= input("  Enter Last Name: ")
birthday= input("   Enter Birthday: ")
gender= input ("     Enter Gender: ")
address= input ("    Enter Address: ")
course= input("     Enter Course: ")
yearLevel= input(" Enter Year Level: ")


print("\n  Full Name: ", firstName, middleName, lastName)
print("   Birthday: ", birthday)
print("     Gender: ", gender)
print("    Address: ", address)
print("     Course: ", course)
print(" Year Level: ", yearLevel)